# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b276b2c5644931c2d608f74887540693de89c0a1df2c9fdcbfa1ad0f5801fee12dd46e79c733243ad9058de184178fe9f899a2a7b77209a3689f9f956fddbbbf

test:
  secret_key_base: e377a8ef88bdf396f05ff9311ef10aa4343fa3761c6b692d698f01757d6677f1812299bbb40765562dcd5e8336c83c9ec8fcf488e8344e5ef878621facade6aa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
